### ISSUE TITLE
It always auto-debugs again after clicking "Disconnect/Stop" button

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-tye#103]
**OS:** Win10
**Build Version:** 20210628.1

**Repro Steps:**

1. Download the project by the command "`git clone https://github.com/pratiksanglikar/tye-demo`" -> Open the project in VS Code -> Select the "Debug with Tye" configuration and F5 -> Click "Disconnect/Stop" button.
2. Check whether stop debugging successfully.

**Expect:**
Stop debugging successfully without any error.

**Actual:**
It always auto-debugs again.
![tye11](https://user-images.githubusercontent.com/62053665/123775277-d2839c00-d900-11eb-870f-81dc936be017.gif)

**More Info:**
This issue doesn't reproduce on the build 20210622.1.

**Comment by philliphoff** [comment]
We reattach the debugger whenever the running application list changes; this was unintentionally done very frequently, resulting in the constant re-attaching shown in the description above.  This was fixed in #107, which should reduce the frequency with which the user sees this issue.  That said, if the user starts/stops Tye applications *other* than the one being debugged, it will cause reattach to occur.

What we need to do is further filter our refresh trigger such that only changes to the application being debugged causes reattach.  (There's still an argument that we shouldn't reattach, ever, if the user has specifically detached from the process, but I'm not sure if VS Code gives us the hooks to make that determination, and will require more investigation.)

**Comment by v-xinda** [comment]
Verified this issue with the latest build 20230320.1, it doesn't reproduce now. So close it.
