### ISSUE TITLE
The project is rebuilt automatically and the debugger is attached again after stopping all services and making changes in a .cs file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-tye#117]
**OS:** Win10
**Build Version:** 20210702.3

**Repro Steps:**

1. Download the project by the command "git clone https://github.com/pratiksanglikar/tye-demo" -> Open the project in VS Code -> Select the "Debug with Tye" configuration and F5.(`"watch": true`)
2. **Click "Disconnect/Stop" button to stop all services**.
3. Navigate to the "EXPLORER" -> Expand the project -> "frontend" folder -> "Pages" folder -> Make changes in the `Index.cshtml.cs` file.
4. Check whether the project is rebuilt automatically and the debugger is attached again.

**Expect:**
The project isn't rebuilt automatically and the debugger isn't attached again.

**Actual:**
The project is rebuilt automatically and the debugger is attached again.
![tye](https://user-images.githubusercontent.com/62053665/124549597-f5aece00-de61-11eb-9728-52163336f62c.gif)

**Comment by philliphoff** [comment]
This is the same issue as #103.  If the user configures the debug launch configuration with `watch` enables, the extension will monitor changes to and re-attach as long as the Tye application is running (which it will be, until the user specifically kills the application).  Unfortunately, it doesn't appear that VS Code provides a way for extensions to know when the user has explicitly killed a debugging session (as opposed to a session ending due to the process being stopped, as it might when in `watch` mode).
